name: Gem Testing
on: push
jobs:
  test_2_7_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the images
        run: RUBY_VERSION=2.7.0 docker-compose build
      - name: Run the tests
        run: RUBY_VERSION=2.7.0 docker-compose up --exit-code-from tests --attach tests
  test_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the images
        run: RUBY_VERSION=latest docker-compose build
      - name: Run the tests
        run: RUBY_VERSION=latest docker-compose up --exit-code-from tests --attach tests
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release
        run: bundle exec gem release
    needs: [test_2_7_0, test_latest]
