name: Gem Testing
on: push
jobs:
  test_2_7_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the images
        run: docker-compose build
      - name: Run the tests
        run: docker-compose up --exit-code-from tests --attach tests
  test_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the images
        run: RUBY_VERSION=latest docker-compose build
      - name: Run the tests
        run: RUBY_VERSION=latest docker-compose up --exit-code-from tests --attach tests