name: Gem Testing
on: push
jobs:
  test_2_7_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the images
        run: RUBY_VERSION=2.7.0 docker-compose build
      - name: Run the tests
        run: RUBY_VERSION=2.7.0 docker-compose up --exit-code-from tests --attach tests
  test_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the images
        run: RUBY_VERSION=latest docker-compose build
      - name: Run the tests
        run: RUBY_VERSION=latest docker-compose up --exit-code-from tests --attach tests
  release:
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main'
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    env:
      RUBY_GEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Determine version type
        id: get_commit_message
        run: |
          message=$(git log -1 --pretty=format:'%s')
          if echo "$message" | grep -iq "fix:"; then
            echo "::set-output name=bump::patch"
          elif echo "$message" | grep -iq "feat:"; then
            echo "::set-output name=bump::minor"
          elif echo "$message" | grep -iq "BREAKING CHANGE:"; then
            echo "::set-output name=bump::major"
          else
            echo "::set-output name=bump::patch"
          fi
      - name: Release
        run: |
          docker build . -t sidekiq_resource_guard
          "echo ---\\n:rubygems_api_key: $RUBY_GEMS_API_KEY\\n:status: :ok\\n > ./credentials"
          docker run --entrypoint "bundle" -v ./credentials:/root/.gem/credentials sidekiq_resource_guard exec gem bump -v ${{ steps.get_commit_message.outputs.bump }} --skip-ci
    needs: [test_2_7_0, test_latest]
